name: "Execute typescript file"
description: "Execute typescript file in the selected repository"
inputs:
  params:
    description: 'Params'
    required: false
    default: "{}"
  script:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute TS file
      uses: michijs/.github/.github/actions/tsscript@main
      with:
        script: michijs/.github/.github/actions/tsscript@main
        params: |
          import { promises as fs } from 'fs';
          import $ from 'bun';
          const scriptText = await (await fetch('${{ inputs.script }}')).text();
          await fs.writeFile('/tmp/temp-script.ts', scriptText);
          const { default: script } = await import('file:///tmp/temp-script.ts');
          const github = ${{ toJson(github) }};
          await script(
          { 
            github, 
            params: ${{ inputs.params }},
          });

            
