name: "Execute typescript file"
description: "Execute typescript file in the selected repository"
inputs:
  params:
    description: 'Params'
    required: false
    default: "{}"
  script:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute TS file
      uses: michijs/.github/.github/actions/tsscript@main
      with:
        script: https://raw.githubusercontent.com/michijs/.github/refs/heads/main/.github/actions/run/main.js
        params: |
          const { default: script } = await import('data:text/javascript,' + encodeURIComponent(await (await fetch(
            '${{ inputs.script }}'
          )).text()));
          await script(
          { 
            github, 
            context, 
            require, 
            core,
            params: ${{ inputs.params }},
          });

            
