name: "Execute typescript file"
description: "Execute typescript file in the selected repository"
inputs:
  params:
    description: "Params"
    required: false
    default: "{}"
  script:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute TS file
      uses: michijs/.github/.github/actions/tsscript@main
      with:
        script: |
          import { write } from "bun";
          async function importScriptFromUrl(url) {
            const fileName = url.split("/").at(-1);
            // Fetch the script
            const res = await fetch(url);
            if (!res.ok) throw new Error(`${url} does not exist (status: ${res.status})`);
            // Write to file
            await write(`/tmp/${fileName}`, await res.blob());
            const { default: script } = await import(`file:///tmp/${fileName}`);
            return (params) => script({ params, github, runGroup });
          }
          const github = ${{ toJson(github) }};
          const script = await importScriptFromUrl("${{ inputs.script }}");
          async function runGroup(name: string, callback: () => Promise<any>) {
            const consoleCalls: Array<any[]> = [];
            const originalConsoleLog = console.log
            let error;
            let result;
            try {
              console.log = (...args) => consoleCalls.push(args);
              result = await callback();
            } catch (e) {
              error = e;
            } finally {
              const isGroup = error || consoleCalls.length > 0;
              console.log = originalConsoleLog;
              console.log(`${isGroup ? "::group::" : ""}${error ? "⛔" : "✅"} ${name}`);
              consoleCalls.forEach((x) => console.log(...x));
              if (error)
                console.log(`::error::${error}`);
              if (isGroup)
                console.log(`::endgroup::`);
              if (error)
                throw error;
              return result;
            }
          }
          await script(${{ inputs.params }});
