name: "Execute typescript file"
description: "Execute typescript file in the selected repository"
inputs:
  params:
    description: "Params"
    required: false
    default: "{}"
  script:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute TS file
      uses: michijs/.github/.github/actions/tsscript@main
      with:
        script: |
          import { promises as fs } from 'fs';
          import $ from 'bun';
          async function importScriptFromUrl(url) {
            const fileName = inputs.script.split('/').at(-1);
            const scriptText = await (await fetch(url)).text();
            await fs.writeFile(`/tmp/${fileName}`, scriptText);
            return await import(`file:///tmp/${fileName}`);
          }
          const github = ${{ toJson(github) }};
          const { default: script } = await importScriptFromUrl('${{ inputs.script }}');
          await script(
          { 
            github, 
            params: ${{ inputs.params }},
          });
