name: "Install packages"
inputs:
  package:
    description: "Package to install"
    type: string
    default: ""
runs:
  steps:
    - name: bun install
      run: bun install ${{ github.event.inputs.package }}
