name: "Install packages"

on: workflow_call
  package:
    description: "Package to install"
    type: string
    default: ""
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Bun install
        run: bun install ${{ github.event.inputs.package }}
