name: "Run command"

on: workflow_call
  inputs:
    command:
      description: "Command to run"
      required: true
      type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Bun run
        run: bun run ${{ github.event.inputs.command }}
