name: "Run command"
inputs:
  command:
    description: "Command to run"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Run
      run: bun run ${{ github.event.inputs.command }}

