name: "Setup runtime"

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        registry-url: 'https://registry.npmjs.org'
