name: "Pull and push changes"
description: "Pull and push changes"
inputs:
  github_token:
    description: "Github token"
    required: true
  tags:
    description: "Tags"
    required: false
  force:
    description: "Force"
    required: false

runs:
  using: "composite"
  steps:
    - name: Pull changes
      shell: bash
      run: git pull origin ${{ github.head_ref || github.ref_name }} --ff-only
    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.head_ref || github.ref_name }}
        tags: ${{ inputs.tags }}
        force: ${{ inputs.force }}
