name: "Pull and push changes"
description: "Pull and push changes"
inputs:
  github_token:
    description: "Github token"
    required: true
  branch:
    description: "Branch name"
    required: true
  tags:
    description: "Tags"
    required: false

runs:
  using: "composite"
  steps:
    - name: Pull changes
      shell: bash
      run: git pull
    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ inputs.branch }}
        tags: ${{ inputs.tags }}
