name: "Pull and push changes"
description: "Pull and push changes"
inputs:
  branch:
    description: "Branch name"
    required: true
  tags:
    description: "Tags"
    required: false
  force:
    description: "Force"
    required: false

runs:
  using: "composite"
  steps:
    - name: Previous git config
      shell: bash
      run: git config pull.rebase false
    - name: Pull changes
      shell: bash
      # Avoids issues if branch does not exist
      continue-on-error: true
      run: git pull origin ${{ inputs.branch }}
    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        branch: ${{ inputs.branch }}
        tags: ${{ inputs.tags }}
        force: ${{ inputs.force }}
