name: "execute-and-lint"
description: "Execute and lint"
inputs:
  script-name:
    description: "Script to execute"
    required: true
  ref:
    description: "Branch to run the script"
    required: false
  github_token:
    description: "Github token"
    required: false
  michijs_bot_app_id:
    description: "Bot app id"
    required: false
  michijs_bot_private_key:
    description: "Bot private key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github_token }}
        persist-credentials: false

    - name: Setup credentials
      uses: michijs/.github/.github/actions/setup-credentials@main
      with:
        github_token: ${{ inputs.github_token }}
        michijs_bot_app_id: ${{ inputs.michijs_bot_app_id }}
        michijs_bot_private_key: ${{ inputs.michijs_bot_private_key }}

    - name: Set up environment
      uses: michijs/.github/.github/actions/setup@main

    - name: Install dependencies
      uses: michijs/.github/.github/actions/install@main

    - name: Run script
      uses: michijs/.github/.github/actions/run@main
      with: 
        command: "${{ inputs.script-name }}"
          
    - name: Run formatter
      uses: michijs/.github/.github/actions/run-linter@main

    # Linter
    - name: Run linter
      uses: michijs/.github/.github/actions/run-linter@main
      with:
        command: check --apply . || true

    # Commit changes
    - name: Commit changes
      uses: michijs/.github/.github/actions/commit-if-changes@main
      with:
        message: "Updated generated types"
        
    # Push repository changes
    - name: Push changes
      uses: michijs/.github/.github/actions/pull-and-push@main