name: "Execute typescript"
description: "Execute typescript in the selected repository"
inputs:
  script:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute ts
      shell: bash
      run: |
        # Executing TS script
        tmpfile="$(mktemp --suffix .ts)"
        cat <<'EOF' > "$tmpfile"
        ${{ inputs.script }}
        EOF
            bun run "$tmpfile"