name: "Execute typescript"
description: "Execute typescript in the selected repository"
inputs:
  script:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute ts
      shell: bash
      run: |
        # Executing TS script
        if [[ "${{ inputs.script }}" == *"'"* ]]; then
          echo "::error::Single quotes are not supported yet (')."
          exit 1
        fi
        bun run - <<'EOF'
          ${{ inputs.script }}
        EOF