name: "Run command"
description: "Run one or multiple commands"
inputs:
  command:
    description: |
      Command(s) to run.
      Examples:
        build
        ["build","test","lint"]
        [{"name":"run typescript tests","script":"test-tsc"}]
    required: true

runs:
  using: "composite"
  steps:
    - name: Run script
      uses: michijs/.github/.github/actions/execute-typescript-file@main
      with:
        script: https://raw.githubusercontent.com/michijs/.github/refs/heads/main/.github/scripts/run.ts
        params: '{command: ${{ fromJSON(inputs.command) }}}'