name: "Run command"
description: "Run one or multiple commands"
inputs:
  command:
    description: |
      Command(s) to run.
      Examples:
        "build"
        ["build","test","lint"]
        [{"name":"run typescript tests","script":"test-tsc"}]
    required: true
  github_token:
    description: "Github token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run script
      uses: michijs/.github/.github/actions/execute-javascript@main
      with:
        github_token: ${{ inputs.github_token }}
        script: https://raw.githubusercontent.com/michijs/.github/refs/heads/main/.github/actions/run/main.js
        params: |
          {
            command: ${{ toJSON(inputs.command) }},
          }
