name: "Run command"
description: "Run command"
inputs:
  command:
    description: "Command to run"
    required: true

runs:
  using: "composite"
  steps:
    - run: bun run ${{ inputs.command }}
      shell: bash

