name: "Dependabot"
description: "Execute dependabot in the selected repository"
inputs:
  repository:
    description: 'Repository to checkout'
    required: false
  ref:
    description: 'Ref to checkout'
    required: false
  github_token:
    description: "Github token"
    required: true
  michijs_bot_app_id:
    description: "Bot app id"
    required: true
  michijs_bot_private_key:
    description: "Bot private key"
    required: true

runs:
  using: "composite"
  steps:
    # Setup
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github_token }}
        persist-credentials: false

    - name: Setup credentials
      uses: michijs/.github/.github/actions/setup-credentials@main
      with:
        github_token: ${{ inputs.github_token }}
        michijs_bot_app_id: ${{ inputs.michijs_bot_app_id }}
        michijs_bot_private_key: ${{ inputs.michijs_bot_private_key }}

    - name: Set up environment
      uses: michijs/.github/.github/actions/setup@main
      
    - name: Get previous package.json state
      shell: bash
      run: echo "OLD_JSON=$(jq -c . package.json)" >> $GITHUB_ENV

    - name: Update dependencies
      shell: bash
      run: |
        echo "UPDATED_PACKAGES=$(bunx npm-check-updates --jsonUpgraded -u -p bun | jq -c .)" >> $GITHUB_ENV
        echo "UPDATED_BETA_PACKAGES=$(bunx npm-check-updates --jsonUpgraded -u -p bun --target greatest --filterVersion '/beta/' | jq -c .)" >> $GITHUB_ENV

    - name: Check for changes
      shell: bash
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes detected. Skipping next steps."
        else
          echo "Changes detected. Proceeding with next steps."
          echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
        fi

    - name: Close old PR and old branch
      shell: bash
      run: |
        gh pr close michijs-dependabot -d || echo "No PR to close"

    - name: Create new branch
      shell: bash
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      run: git checkout -B michijs-dependabot

    - name: Commit changes
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      uses: michijs/.github/.github/actions/commit-if-changes@main
      with:
        message: "Michijs Dependabot changes"

    - name: push changes
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      uses: ad-m/github-push-action@v0.8.0
      with:
        repository: ${{ inputs.repository }}
        branch: michijs-dependabot
        force: true

    - name: Create new PR
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      uses: michijs/.github/.github/actions/execute-javascript@main
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        script: https://raw.githubusercontent.com/michijs/.github/refs/heads/main/.github/actions/dependabot/main.js
        params: |
          {
            ref: "${{ inputs.ref || 'master' }}",
            githubRepository: "${{ inputs.repository || env.GITHUB_REPOSITORY }}",
            updatedPackages: {...JSON.parse(process.env.UPDATED_PACKAGES), ...JSON.parse(process.env.UPDATED_BETA_PACKAGES)},
            oldJson: process.env.OLD_JSON
          }
