name: "Dependabot"
description: "Execute dependabot in the selected repository"
inputs:
  repository:
    description: 'Repository to checkout'
    required: false
  ref:
    description: 'Ref to checkout'
    required: false
  github_token:
    description: "Github token"
    required: true

runs:
  using: "composite"
  steps:
    # Setup
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github_token }}

    # Configure Git
    - name: Git configuration
      uses: michijs/.github/.github/actions/set-git-config-github-actions@main

    - name: Set up environment
      uses: michijs/.github/.github/actions/setup@main
      with:
        github_token: ${{ inputs.github_token }}
      
    - name: Get previous package.json state
      shell: bash
      run: echo "OLD_JSON=$(jq -c . package.json)" >> $GITHUB_ENV

    - name: Update dependencies
      shell: bash
      run: |
        echo "UPDATED_PACKAGES=$(bunx npm-check-updates --jsonUpgraded -u -p bun | jq -c .)" >> $GITHUB_ENV
        echo "UPDATED_BETA_PACKAGES=$(bunx npm-check-updates --jsonUpgraded -u -p bun --target greatest --filterVersion '/beta/' | jq -c .)" >> $GITHUB_ENV

    - name: Check for changes
      shell: bash
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes detected. Skipping next steps."
        else
          echo "Changes detected. Proceeding with next steps."
          echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
        fi

    - name: Close old PR and old branch
      shell: bash
      run: |
        gh pr close michijs-dependabot -D || echo "No PR to close"

    - name: Create new branch
      shell: bash
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      run: git checkout -B michijs-dependabot

    - name: Commit changes
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      uses: michijs/.github/.github/actions/commit-if-changes@main
      with:
        message: "Michijs Dependabot changes"

    - name: push changes
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      uses: ad-m/github-push-action@v0.8.0
      with:
        repository: ${{ inputs.repository }}
        branch: michijs-dependabot
        force: true

    - name: Create new PR
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      uses: actions/github-script@v7
      with:
        script: |
          const { default: script } = await import('data:text/javascript,' + encodeURIComponent(await (await fetch(
            'https://raw.githubusercontent.com/michijs/.github/refs/heads/main/.github/actions/dependabot/dependabot.js'
          )).text()));
          await script(
          { 
            github, 
            context, 
            require, 
            params: {
              githubRepository: "${{ inputs.repository || env.GITHUB_REPOSITORY }}",
              updatedPackages: {...JSON.parse(process.env.UPDATED_PACKAGES), ...JSON.parse(process.env.UPDATED_BETA_PACKAGES)},
              oldJson: process.env.OLD_JSON
            },
          });

            
