name: "Set GIT config Github actions"
description: "Set GIT config Github actions"
inputs:
  github_token:
    description: "Github token"
    required: false
  michijs_bot_app_id:
    description: "Bot app id"
    required: false
  michijs_bot_private_key:
    description: "Bot private key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get credentials
      id: get-credentials
      uses: michijs/.github/.github/actions/get-credentials@main
      with:
        github_token: ${{ inputs.github_token }}
        michijs_bot_private_key: ${{ inputs.michijs_bot_private_key }}
        michijs_bot_app_id: ${{ inputs.michijs_bot_app_id }}
    - name: Set credentials
      uses: michijs/.github/.github/actions/set-credentials@main
      with:
        github_token: ${{ steps.get-credentials.outputs.github_token }}
        email: ${{ steps.get-credentials.outputs.email }}
        name: ${{ steps.get-credentials.outputs.name }}