name: "Set GIT config Github actions"
description: "Set GIT config Github actions"
inputs:
  github_token:
    description: "Github token"
    required: false
  michijs_bot_app_id:
    description: "Bot app id"
    required: false
  michijs_bot_private_key:
    description: "Bot private key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate a token (if possible)
      id: generate-token
      if: ${{ inputs.michijs_bot_private_key != '' && inputs.michijs_bot_app_id != '' }}
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.michijs_bot_app_id }}
        private-key: ${{ inputs.michijs_bot_private_key }}
        owner: ${{ github.repository_owner }}
    - name: Set default github token
      shell: bash
      if: ${{ steps.generate-token.outputs.token || inputs.github_token }}
      run: |
        echo "GITHUB_TOKEN=${{ steps.generate-token.outputs.token || inputs.github_token }}" >> $GITHUB_ENV
    - name: Get GitHub App User ID
      id: get-user-id
      if: ${{ steps.app-token.outputs.app-slug != ''}}
      shell: bash
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Git configuration
      shell: bash
      if: ${{ inputs.michijs_bot_private_key != '' && inputs.michijs_bot_app_id != '' }}
      run: |
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
      
    - name: Git default configuration
      shell: bash
      if: ${{ inputs.michijs_bot_private_key == '' && inputs.michijs_bot_app_id == '' %% github_token != '' }}
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"


