name: "Install packages"
description: "Install packages"
inputs:
  github_token:
    description: "Github token"
    required: true
  package:
    description: "Package to install"
    default: ""
runs:
  using: "composite"
  steps:
    # Telling bun were to find @michijs private packages
    - run: echo "[install.scopes]\n\"@michijs\" = { token = \"${{ inputs.github_token }}\", url = \"https://npm.pkg.github.com\" }" > $HOME/.bunfig.toml
      shell: bash
    - run: bun install ${{ inputs.package }}
      shell: bash