name: "Install packages"
description: "Install packages"
inputs:
  github_token:
    description: "Github token"
    required: true
  package:
    description: "Package to install"
    default: ""
runs:
  using: "composite"
  steps:
    # - run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.github_token }}\n@michijs:registry=https://npm.pkg.github.com" > ~/.npmrc
    #   shell: bash
    # - run: npm install
    #   shell: bash
    - run: bun install ${{ inputs.package }}
      env:
        BUN_AUTH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      # Cleaning
    - run: rm ./bunfig.toml || true
      shell: bash
