name: "Install packages"
description: "Install packages"
inputs:
  package:
    description: "Package to install"
    default: ""
runs:
  using: "composite"
  steps:
    # - run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.github_token }}\n@michijs:registry=https://npm.pkg.github.com" > ~/.npmrc
    #   shell: bash
    # - run: npm install
    #   shell: bash
    # Save the current bunfig.toml
    - run: bun install ${{ inputs.package }}
      shell: bash
