name: "Install packages"
inputs:
  package:
    description: "Package to install"
    type: string
    default: ""
runs:
  using: "composite"
  steps:
    - run: bun install ${{ inputs.package }}
      shell: bash