name: "Install packages"
description: "Install packages"
inputs:
  github_token:
    description: "Github token"
    required: true
  package:
    description: "Package to install"
    default: ""
runs:
  using: "composite"
  steps:
    - run: bun install ${{ inputs.package }}
      env:
        BUN_AUTH_TOKEN: ${{ inputs.github_token }}
      shell: bash