name: "Execute script"
description: "Execute script"
inputs:
  script-name:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    - name: Set up environment
      uses: michijs/.github/.github/actions/setup@main

    - name: Install dependencies
      uses: michijs/.github/.github/actions/install@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run script
      uses: michijs/.github/.github/actions/run@main
      with: 
        command: ${{ inputs.script-name }}

