name: "Execute script"
description: "Execute script"
inputs:
  script-name:
    description: "Script to execute"
    required: true
  github_token:
    description: "Github token"
    required: true
  ref:
    description: "Branch to run the script"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github_token }}

    - name: Set up environment
      uses: michijs/.github/.github/actions/setup@main
      with:
        github_token: ${{ inputs.github_token }}

    - name: Install dependencies
      uses: michijs/.github/.github/actions/install@main
      with:
        github_token: ${{ inputs.github_token }}

    - name: Run script
      uses: michijs/.github/.github/actions/run@main
      with: 
        command: ${{ inputs.script-name }}
        github_token: ${{ inputs.github_token }}