name: "Run lint"
description: "Runs linter on the project"
inputs:
  github_token:
    description: "Github token"
    required: false
  michijs_bot_app_id:
    description: "Bot app id"
    required: false
  michijs_bot_private_key:
    description: "Bot private key"
    required: false

runs:
  using: "composite"
  steps:
    # Setup
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.github_token }}
        persist-credentials: false

    - name: Get Branch Name
      shell: bash
      run: echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

    # Configure Git
    - name: Setup credentials
      uses: michijs/.github/.github/actions/setup-credentials@main
      with:
        github_token: ${{ inputs.github_token }}
        michijs_bot_app_id: ${{ inputs.michijs_bot_app_id }}
        michijs_bot_private_key: ${{ inputs.michijs_bot_private_key }}

    - name: Set up environment
      uses: michijs/.github/.github/actions/setup@main

    - name: Run formatter
      uses: michijs/.github/.github/actions/run-linter@main

    # Linter
    - name: Run linter
      uses: michijs/.github/.github/actions/run-linter@main
      with:
        command: check --apply . || true

    - name: Check for changes
      shell: bash
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes detected. Skipping next steps."
        else
          echo "Changes detected. Proceeding with next steps."
          echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
        fi

    - name: Close old PR and old branch
      shell: bash
      run: |
        gh pr close lint/${{ env.BRANCH_NAME }} || echo "No PR to close"
        git branch -D origin/lint/${{ env.BRANCH_NAME }} --remote || echo "No branch to delete"

    - name: Create new branch
      shell: bash
      if: env.CHANGES_DETECTED == 'true'
      run: git checkout -B lint/${{ env.BRANCH_NAME }}

    - name: Commit changes
      if: env.CHANGES_DETECTED == 'true'
      uses: michijs/.github/.github/actions/commit-if-changes@main
      with:
        message: "Linting changes"

    - name: push changes
      if: env.CHANGES_DETECTED == 'true'
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        branch: lint/${{ env.BRANCH_NAME }}
        force: true

    - name: Create pull request
      shell: bash
      if: env.CHANGES_DETECTED == 'true'
      run: |
        SUGGESTIONS=$(biome check . 2>&1 || true)
        gh pr create -B ${{ env.BRANCH_NAME }} -H lint/${{ env.BRANCH_NAME }} --title '[${{ env.BRANCH_NAME }}] Linting changes' --body "This pull request includes linting changes based on the target branch.

        Please review and merge if everything looks good.

        <details>
          <summary>Additional suggestions:</summary>
          ${SUGGESTIONS}
        </details>
        "

    - name: Detect if token is a PAT
      shell: bash
      if: env.CHANGES_DETECTED == 'true'
      run: |
        if [[ "${{ env.GITHUB_TOKEN }}" =~ ^gh(p|o|u|r)_ ]]; then
          echo "IS_PAT=true" >> $GITHUB_ENV
          echo "Detected token is a PAT"
        else
          echo "IS_PAT=false" >> $GITHUB_ENV
          echo "Detected token is likely GITHUB_TOKEN"
        fi

    - name: "Run tests"
      uses: michijs/.github/.github/actions/run-tests@main
      if: ${{ env.IS_PAT == 'false' && env.CHANGES_DETECTED == 'true' }}
      continue-on-error: true
      with:
        ref: lint/${{ env.BRANCH_NAME }}
