name: "Run lint"
description: "Runs linter on the project"
inputs:
  command:
    description: "Command to run"
    default: "format --write --json ."

runs:
  using: "composite"
  steps:
    - name: Setup Biome
      uses: michijs/.github/.github/actions/install@main
      with: 
        package: -g @biomejs/biome

    - name: Import Biome config file
      shell: bash
      run: wget -O biome.json https://raw.githubusercontent.com/michijs/.github/main/biome.json

    - name: Run Biome
      shell: bash
      run: biome ${{ inputs.command }}

    - name: Remove biome file
      shell: bash
      run: rm biome.json

