name: "Set GIT config michijs[bot]"
description: "Set GIT config michijs[bot]"

runs:
  using: "composite"
  steps:
    - name: Git configuration
      shell: bash
      run: |
        git config --global user.email "1814196+michijs[bot]@users.noreply.github.com"
        git config --global user.name "michijs[bot]"

