name: "Run tests"
description: "Run tests"
inputs:
  github_token:
    description: "Github token"
    required: false
  scripts:
    description: 'JSON array of scripts with name and script fields'
    required: true
  ref:
    description: 'Git ref to checkout'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check if PR exists for branch
      if: inputs.ref != ''
      id: pr-check
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        result-encoding: string
        script: |
          const branch = "${{ inputs.ref }}";
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const head = `${owner}:${branch}`;

          const pulls = await github.rest.pulls.list({
            owner,
            repo,
            head,
            state: 'open',
            per_page: 1
          });

          core.setOutput(
            'pr',
            pulls.data.length > 0 ? JSON.stringify(pulls.data[0]) : ""
          );

    - name: Run scripts
      uses: michijs/.github/.github/actions/execute-script@main
      id: execute
      continue-on-error: ${{ steps.pr-check.outputs.pr != '' }}
      with:
        github_token: ${{ inputs.github_token }}
        script-name: ${{ inputs.scripts }}

    - name: Comment on PR
      if: steps.pr-check.outputs.pr != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const failed = "${{ steps.execute.outcome }}" === 'failure';
          const pr = ${{ steps.pr-check.outputs.pr }};
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number,
            body: `${pr.body}\n\n${
              failed
                ? "🔴❌ FAILURE > Some tests failed. Please [Review the logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true)."
                : "🟢✅ SUCCESS > All tests passed successfully."
            }`,
          });
