name: Deploy
on:
  workflow_call:
    inputs:
      ref:
        description: "Branch to run the script"
        type: string
        required: false
permissions:
  contents: write
  pull-requests: write 

jobs:
  Run:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master' || inputs.ref == 'master'
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # Configure Git
      - name: Git configuration
        uses: michijs/.github/.github/actions/set-git-config-github-actions@main

      - name: Set up environment
        uses: michijs/.github/.github/actions/setup@main

      - name: Create new branch
        run: git checkout -B production

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.github_token }}
          branch: production
          force: true