name: Deploy
on:
  workflow_call:
permissions:
  contents: write
  pull-requests: write 

jobs:
  Run:
    runs-on: ubuntu-latest
    if: github.head_ref == 'master'
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # Configure Git
      - name: Git configuration
        uses: michijs/.github/.github/actions/set-git-config-github-actions@main

      - name: Set up environment
        uses: michijs/.github/.github/actions/setup@main

      - name: Create new branch
        run: git checkout -B production

      - name: Push changes
        uses: michijs/.github/.github/actions/pull-and-push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: production