name: Execute script
on:
  workflow_call:
    inputs:
      script-name:
        description: "Script to execute"
        type: string
        required: true
  
jobs:
  Run:
    # TODO: Use ubuntu-latest when bun test fix their issue
    runs-on: macos-latest
    # runs-on: windows-latest
    steps:
      - name: Execute script
        uses: michijs/.github/.github/actions/execute-script@main
        with: 
          script-name: ${{ inputs.script-name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
