name: Execute script
on:
  workflow_call:
    inputs:
      script-name:
        description: "Script to execute"
        type: string
        required: true
      skip:
        description: "Should be skipped"
        type: boolean
        required: false
  
jobs:
  Run:
    if: inputs.skip != 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Execute script
        uses: michijs/.github/.github/actions/execute-script@main
        with: 
          script-name: ${{ inputs.script-name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
