name: Execute script
on:
  workflow_call:
    inputs:
      script-name:
        description: "Build script to execute"
        type: string
        required: true

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

        # Setup Node.js environment
      - name: Set up Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0

      - name: Install dependencies
        run: npm install

      # Build
      - name: Execute script
        run: npm run ${{ inputs.script-name }}
