name: Execute script
on:
  workflow_call:
    inputs:
      script-name:
        description: "Script to execute"
        type: string
        required: true
      ref:
        description: "Branch to run the script"
        type: string
        required: false
  
permissions:
  contents: write

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Execute script
        uses: michijs/.github/.github/actions/execute-script@main
        with: 
          script-name: ${{ inputs.script-name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
