name: Lint
on:
  workflow_call:
permissions:
  contents: write
  pull-requests: write 

jobs:
  Run:
    runs-on: ubuntu-latest
    if: >
      !startsWith(github.ref_name, 'lint/') &&
      !startsWith(github.ref_name, 'michijs-dependabot') &&
      !startsWith(github.ref_name, 'dependabot') &&
      github.ref_name != 'production'
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Branch Name
        run: echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          
      # Configure Git
      - name: Git configuration
        uses: michijs/.github/.github/actions/set-git-config-github-actions@main

      - name: Set up environment
        uses: michijs/.github/.github/actions/setup@main

      - name: Run formatter
        uses: michijs/.github/.github/actions/lint@main
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Linter

      - name: Run linter
        uses: michijs/.github/.github/actions/lint@main
        with: 
          command: check --apply . || true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Skipping next steps."
          else
            echo "Changes detected. Proceeding with next steps."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          fi
          
      - name: Close old PR
        continue-on-error: true
        run: 
          gh pr close lint/${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old branch
        continue-on-error: true
        run: 
          git branch -D lint/${{ env.BRANCH_NAME }} --remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new branch
        if: env.CHANGES_DETECTED == 'true'
        run: git checkout -B lint/${{ env.BRANCH_NAME }}

      - name: Commit changes
        if: env.CHANGES_DETECTED == 'true'
        uses: michijs/.github/.github/actions/commit-if-changes@main
        with:
          message: "Linting changes"

      - name: push changes
        if: env.CHANGES_DETECTED == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: lint/${{ env.BRANCH_NAME }}
          force: true

      - name: Create pull request
        if: env.CHANGES_DETECTED == 'true'
        run: |
            SUGGESTIONS=$(biome check . 2>&1 || true)
            gh pr create -B ${{ env.BRANCH_NAME }} -H lint/${{ env.BRANCH_NAME }} --title '[${{ env.BRANCH_NAME }}] Linting changes' --body "This pull request includes linting changes based on the target branch.

            Please review and merge if everything looks good.
            
            <details>
              <summary>Additional suggestions:</summary>
              ${SUGGESTIONS}
            </details>
            "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
