name: Lint
on:
  workflow_call:
permissions:
  contents: write
  pull-requests: write 

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name: Get Branch Name
        run: echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      # Configure Git
      - name: Git configuration
        uses: michijs/.github/.github/actions/set-git-config-github-actions@main

      - name: Set up environment
        uses: michijs/.github/.github/actions/setup@main

      - name: Run formatter
        uses: michijs/.github/.github/actions/lint@main

      - name: Commit changes
        uses: michijs/.github/.github/actions/commit-if-changes@main
        with:
          message: "Format changes"

      - name: Push changes
        uses: michijs/.github/.github/actions/pull-and-push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Linter
      - name: Check if branch contains 'dependabot'
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == *dependabot* ]]; then
            echo "Branch contains 'dependabot'. Linter will not run."
            echo "DEPENDABOT_DETECTED=true" >> $GITHUB_ENV
          else
            echo "Branch does not contain 'dependabot'. Linter will run."
          fi

      - name: Run linter
        if: env.DEPENDABOT_DETECTED != 'true'
        uses: michijs/.github/.github/actions/lint@main
        with: 
          command: check --apply . || true

      - name: Check for changes
        if: env.DEPENDABOT_DETECTED != 'true'
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Skipping next steps."
          else
            echo "Changes detected. Proceeding with next steps."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          fi

      - name: Delete existing branch (if exists)
        if: env.DEPENDABOT_DETECTED != 'true'
        run: |
          git push origin --delete ${{ env.BRANCH_NAME }}_lint || true

      - name: Create new branch
        if: env.CHANGES_DETECTED == 'true'
        run: git checkout -b ${{ env.BRANCH_NAME }}_lint

      - name: Commit changes
        if: env.CHANGES_DETECTED == 'true'
        uses: michijs/.github/.github/actions/commit-if-changes@main
        with:
          message: "Linting changes"

      - name: Push changes
        if: env.CHANGES_DETECTED == 'true'
        uses: michijs/.github/.github/actions/pull-and-push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: ${{ env.BRANCH_NAME }}_lint

      - name: Create pull request
        if: env.CHANGES_DETECTED == 'true'
        continue-on-error: true
        run: |
            SUGGESTIONS=$(biome check --json . 2>&1 || true)
            gh pr create -B ${{ env.BRANCH_NAME }} -H ${{ env.BRANCH_NAME }}_lint --title '[${{ env.BRANCH_NAME }}] Linting changes' --body "This pull request includes linting changes based on the target branch.

            Please review and merge if everything looks good.
            
            <details>
              <summary>Additional suggestions:</summary>
              ${SUGGESTIONS}
            </details>
            "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
