name: Michijs dependabot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  list-repositories:
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.list-repositories.outputs.repositories }}
    steps:
      - name: List org repositories
        id: list-repositories
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          result-encoding: string
          script: |
            const { data } = await github.rest.repos.listForOrg({ org: "michijs" });
            const repositories = data.map(r => ({
              name: r.name,
              full_name: r.full_name,
              archived: r.archived,
              disabled: r.disabled,
              default_branch: r.default_branch
            }));
            core.setOutput('repositories', JSON.stringify(repositories));
  run-dependabot:
    runs-on: ubuntu-latest
    needs: list-repositories
    strategy:
      matrix:
        repository: ${{ fromJson(needs.list-repositories.outputs.repositories) }}
    steps:
      - name: "Run dependabot on ${{matrix.repository.name}}"
        uses: michijs/.github/.github/actions/dependabot@main
        if: ${{ matrix.repository.archived == 'false' && matrix.repository.disabled == 'false' }}
        with:
          github_token: ${{ secrets.PAT }}
          repository: ${{ matrix.repository.full_name }}
          ref: ${{ matrix.repository.default_branch }}
            
