name: Michijs dependabot
on:
  workflow_dispatch:

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: List org repositories
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const result = await github.rest.repos.listForOrg({org: "michijs"});
            console.log({result})

            
