name: Take screenshots
on:
  workflow_dispatch:
    inputs:
      pages:
        description: Provide the pages in stringified array format
        required: true
        type: string
        default: "https://google.com/,https://github.com/"
jobs:
  convert-string-to-array:
    runs-on: ubuntu-latest
    outputs:
      ARRAY: ${{ steps.convert-string-to-array-step.outputs.ARRAY }}
    steps:
      - name: Convert string to array
        id: convert-string-to-array-step
        run: echo ARRAY=$(echo "${{ github.event.inputs.pages }}" | jq -R 'split(",")') >> "$GITHUB_OUTPUT"
        
  take-screenshots:
    needs: convert-string-to-array
    runs-on: ubuntu-latest
    name: "Take screenshot of ${{ matrix.PAGE }}"
    env:
      TARGET_URL: ${{ matrix.PAGE }}
    strategy:
      fail-fast: false
      matrix:
        PAGE: ${{fromJSON(needs.convert-string-to-array.outputs.ARRAY)}}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run print-mode screenshot script
        run: node take-print-screenshot.js
        
      - name: Get artifact name
        run: |
          filename=$(basename "${{matrix.PAGE}}")
          echo "ARTIFACT_NAME=$(echo "$filename" | tr -d '/:?')" >> $GITHUB_ENV

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          path: screenshots
          name: "Screenshot_${{ env.ARTIFACT_NAME }}"
          retention-days: 1
