name: Take screenshots
on:
  workflow_dispatch:
    inputs:
      pages:
        description: Provide the pages in stringified array format
        required: true
        type: string
        default: "https://google.com/,https://github.com/"
jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    name: "${{ matrix.PAGE }}"
    strategy:
      fail-fast: false
      matrix:
        PAGE: ${{fromJSON(format('[{0}]'', github.event.inputs.pages)) }}
    steps:
      - name: Print page
        run: echo "${{ matrix.PAGE }}"